project:
  type: book

book:
  title: "Introduction to Computational Evolutionary Biology"
  author: "Fabricio Almeida-Silva and Yves Van de Peer"
  date: "2023"
  chapters:
    - index.qmd
    - chapters/intro_to_R.qmd
    - chapters/data_structures_genomics.qmd
    - chapters/phylogeny_inference_distance.qmd
    - chapters/phylogeny_inference_ml.qmd

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source